name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log Environment Variables
        run: |
          echo "AWS_REGION: ${{ secrets.AWS_REGION }}"
          echo "BUCKET_NAME: ${{ secrets.BUCKET_NAME }}"
          echo "DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_region: ${{ secrets.AWS_REGION }}
          TF_VAR_bucket_name: ${{ secrets.BUCKET_NAME }}
          TF_VAR_domain_name: ${{ secrets.DOMAIN_NAME }}
        run: terraform apply -auto-approve
